### ISSUE TITLE
Toggle Component: updating 'checked' prop doesn't rerender component

### ISSUE THREAD

**Issue by DevineJasper** [digipolisantwerp/acpaas-ui_react#197] opened 2021-01-28 11:00 UTC
## Problem

Passing a dynamic 'checked' prop to the Toggle element, using the useState hook, doesn't change the checked status of the component.

## To Reproduce

```
const [isChecked, setIsChecked] = useState(false);

<Button
  onClick={(e: any) => {
    handleSubmit(e);
    setIsChecked(!isChecked);
  }}
>
<Toggle
  checked={isChecked}
  onClick={() => {
    toggleFilters();
    setIsChecked(!isChecked);
  }}
 type="primary"
  checkedIcon="fa-filter"
  checkedLabel="Toon filters"
  uncheckedLabel="Verberg"
/>
```

## Expected behavior

When clicking the Button or Toggle, the 'checked' state of the Toggle is changed.

## OS (please complete the following information):

 - Device: Mabook Pro
 - OS: macOS Catalina 10.15.7
 - Browser Microsoft Edge
 - Version 88.0.705.50

**Comment by maartenraes** [comment] 2021-01-28 11:09
Suspect that instead of `defaultChecked={this.state.checked}` it should be `checked={this.state.checked}`
Right now controlled input is getting mixed with uncontrolled input. 

```
 <input
          className="a-toggle__checkbox"
          id={id}
          name={name}
          aria-checked={this.state.checked}
          defaultChecked={this.state.checked}
          type="checkbox"
          role="switch"
          onChange={this.handleClick}
        />
```

@TriangleJuice do you suspect updating this will cause any side-effects? If so we can create a pull request for this.

**Comment by maartenraes** [comment] 2021-01-28 11:14
More info: https://reactjs.org/docs/uncontrolled-components.html#default-values

**Comment by TriangleJuice** [comment] 2021-02-15 14:48
@maartenraes I have issued a PR to address this problem. You're welcome to leave your comments.

**Comment by TriangleJuice** [comment] 2021-02-19 07:56
Fixed in #216

**Closed by TriangleJuice** 2021-02-19 07:56 UTC

**Comment by maartenraes** [comment] 2021-02-22 13:31
@TriangleJuice can we reopen this issue, the problem is still an issue. 
We're unable to overwrite the current checked value in the state by providing a new value to `checked` when trying to control the component from somewhere else

**Comment by maartenraes** [comment] 2021-03-03 13:46
Reproduction case: 
https://stackblitz.com/edit/react-x77zse?file=src/App.js
